### ISSUE TITLE
Exception in workitem.setCustomField

### ISSUE THREAD

**Issue by rotkiv1205** [jesper-raemaekers/python-polarion#106]
# Trying to use function setCustomField but failing at self.save()
```
workitem.setCustomField(key='Interval',value='NA')

Traceback (most recent call last):


File "\env\Lib\site-packages\polarion\base\custom_fields.py", line 37, in setCustomField
    self.save()
  File "\env\Lib\site-packages\polarion\workitem.py", line 565, in save
    service.updateWorkItem(updated_item)
  File "\env\Lib\site-packages\zeep\proxy.py", line 46, in __call__
    return self._proxy._binding.send(
  File "\env\Lib\site-packages\zeep\wsdl\bindings\soap.py", line 135, in send
    return self.process_reply(client, operation_obj, response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\env\Lib\site-packages\zeep\wsdl\bindings\soap.py", line 229, in process_reply
    return self.process_error(doc, operation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\env\Lib\site-packages\zeep\wsdl\bindings\soap.py", line 329, in process_error
    raise Fault(
zeep.exceptions.Fault: java.lang.IllegalArgumentException: type cannot be null
```

Got any idea of that the cause could be from just looking at this or would more info be required? I'm at a loss of what the issue here can be.

**Comment by rotkiv1205** [comment]
id:
string_field
Name:
string_field
Type:
Text (multi line)

**Comment by jesper-raemaekers** [comment]
Hi,

I managed to get the same error after changing the custom field type to match yours. The error is really poor, but it is caused by a string being the wrong value for a multi line text field. Try submitting your string like this:
```
workitem.setCustomField(key='string_field', value=pol.TextType(type='text/plain', content='NA', contentLossy=False))
```

where pol is the Polarion object:
```
pol = polarion.Polarion('http://localhost/polarion', '', '')
```

**Comment by rotkiv1205** [comment]
Solved it, thanks!
