### ISSUE TITLE
Error retrieving existing Test Run

### ISSUE THREAD

**Issue by ppoon-cm** [jesper-raemaekers/python-polarion#19]
At https://python-polarion.readthedocs.io/en/latest/testrun.html, there is an example of how to get a test run:  `existing_test_run = self.checking_project.getTestRun('test-id')`.  I'm able to get my Project and modify a Work Item.

However, when attempting to `test_run = project.getTestRun('ABC-123')`, I get the error below.  FWIW, I'm using Python 3.9.6 on macOS Catalina (10.15.7) if that is a factor.

Any suggestions on how to resolve this?  Thanks!

```
Exception ignored in: <function Polarion.__del__ at 0x10d4f89d0>
Traceback (most recent call last):
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/site-packages/polarion/polarion.py", line 43, in __del__
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/site-packages/zeep/proxy.py", line 46, in __call__
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/site-packages/zeep/wsdl/bindings/soap.py", line 127, in send
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/site-packages/zeep/transports.py", line 107, in post_xml
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/site-packages/zeep/transports.py", line 73, in post
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/site-packages/requests/sessions.py", line 532, in request
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/site-packages/requests/sessions.py", line 711, in merge_environment_settings
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/site-packages/requests/utils.py", line 776, in get_environ_proxies
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/site-packages/requests/utils.py", line 760, in should_bypass_proxies
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/urllib/request.py", line 2647, in proxy_bypass
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/urllib/request.py", line 2624, in proxy_bypass_macosx_sysconf
  File "/Users/ppoon/anaconda3/envs/polarion/lib/python3.9/urllib/request.py", line 2566, in _proxy_bypass_macosx_sysconf
ImportError: sys.meta_path is None, Python is likely shutting down

```

**Comment by jesper-raemaekers** [comment]
It looks like it's crashing when the program had ended and the Polarion object needs to be deleted. Can you see if the problem is actually caused by getting the test run?
So maybe add a print(existing_test_run) or a break point before letting the program exit.

**Comment by ppoon-cm** [comment]
Oddly, the problem just resolved itself.  I retried this morning, and it ran successfully.  Apologies for the false alarm, and thanks for the quick response.  Also, thanks for creating this library!  Cheers!

**Comment by ppoon-cm** [comment]
Issue resolved itself.
