### ISSUE TITLE
https support?

### ISSUE THREAD

**Issue by bjahnke** [jesper-raemaekers/python-polarion#44]
I am unable to connect to our polarion server with this library after we updated to https (full stack trace bellow). I'm not too knowledgeable with SSL certificates, so I'm not sure if this is an issue on our end or a limitation of the library. I dug this up after some research: 

https://stackoverflow.com/questions/10667960/python-requests-throwing-sslerror

Per the link, perhaps a fix would be to expose the verify parameter of requests.get through new parameter for the Polarion class init. This would allow applications to specify a path to the certificate's .pem file or skip verification altogether. 

I would appreciate your input.

Traceback (most recent call last):
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\bjahnke\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\bjahnke\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\bjahnke\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='polarion.redacted.com', port=443): Max retries exceeded with url: /polarion/ws/services (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)')))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\_projects\polarion_api_test\venv\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='polarion.redacted.com', port=443): Max retries exceeded with url: /polarion/ws/services (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1122)')))
python-BaseException

**Comment by Futsch1** [comment]
You seem to use a self-signed SSL certificate. You can skip the certificate validation by setting the parameter skip_cert_verification in the Polarion object constructor.

`polarion = polarion.Polarion(url, username, password, skip_cert_verification=True)`

**Comment by bjahnke** [comment]
Thanks for getting back to me. Looks like I didn't have the most updated version of the package, so I didn't see skip_cert_verification. However, upgrading through pip does not give me the latest package. I've tried:
- pip install --upgrade polarion
- pip install --upgrade --force-reinstall
- pip uninstall polarion, pip install polarion
- pip uninstall polarion, pip install --no-cache-dir polarion

I was able to install the latest package downloading your repo and installing via setup.py locally. I typically have this issue installing my own packages when I update code but forget to change the version number in setup.py. Not sure if that's the issue here though.

**Comment by Futsch1** [comment]
Yes, it seems that the pip package does not reflect the latest changes in the repo. You can clone the git repo and copy the "polarion" subfolder (or just download it from github) into the project where you import it and use it directly until @jesper-raemaekers  updates the pip package.

**Comment by jesper-raemaekers** [comment]
Just a comment on that because I've been not active much lately.
I'm getting the build pipeline setup better (you have have a look here i think: https://dev.azure.com/jraemaekers/Python%20Polarion/_build/results?buildId=227&view=results). The tests used to be ran against a virtual machine on my local desktop which only has a trial license of Polarion. This was troublesome as every 30 days the trial would expire and the build pipeline would fail.

Now I've setup a VPS with Hetzner which can start a docker based instance of Polarion every time a build is run. This instance has a default set of data which makes sure the tests start with the same data set in the test project. Doing so I've discovered an issue that must be fixed as it now fails some tests.

@Futsch1 Thanks for commenting on some issues here. It is much appreciated. I'll be able to release a new version "soon".

**Comment by jesper-raemaekers** [comment]
This was fixed in 0.3.0
