### ISSUE TITLE
automatic query of test steps raises server side exception

### ISSUE THREAD

**Issue by ergorion** [jesper-raemaekers/python-polarion#57]
It seems that whenever I query a work item, at the end there is an additional call to getTestSteps. Unfortunately, this raises a server side exception, that is only visible if you used log level DEBUG. Is there a way to make this call to getTestSteps optional?

2022-03-29 10:28:29 DEBUG    HTTP Post to https://server/polarion/ws/services/TestManagementWebService:
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"><soap-env:Header><ns1:sessionID xmlns:ns1="http://ws.polarion.com/session" soap-env:actor="http://schemas.xmlsoap.org/soap/actor/next" soap-env:mustUnderstand="0">-46616533766877033</ns1:sessionID></soap-env:Header><soap-env:Body><ns0:getTestSteps xmlns:ns0="http://ws.polarion.com/TestManagementWebService-impl"><ns0:uri>subterra:data-service:objects:/default/prefix_trunk${WorkItem}prefix-53229</ns0:uri></ns0:getTestSteps></soap-env:Body></soap-env:Envelope>
2022-03-29 10:28:29 DEBUG    Resetting dropped connection: server
2022-03-29 10:28:29 DEBUG    https://server:443 "POST /polarion/ws/services/TestManagementWebService HTTP/1.1" 500 None
2022-03-29 10:28:29 DEBUG    HTTP Response from https://server/polarion/ws/services/TestManagementWebService (status: 500):
<?xml version="1.0" encoding="utf-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><soapenv:Fault><faultcode>soapenv:Server.userException</faultcode><faultstring>java.lang.IllegalArgumentException: testCase does not have a test steps field defined: PObject(WorkItem; subterra:data-service:objects:/default/prefix_trunk${WorkItem}prefix-53229)</faultstring><detail><ns1:stackTrace xmlns:ns1="http://xml.apache.org/axis/">java.lang.IllegalArgumentException: testCase does not have a test steps field defined: PObject(WorkItem; subterra:data-service:objects:/default/prefix_trunk${WorkItem}prefix-53229)
	at com.polarion.alm.tracker.internal.TestManagementService.setTestSteps(TestManagementService.java:444)
	at com.polarion.alm.ws.services.TestManagementWebService.getTestSteps(TestManagementWebService.java:418)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
....

**Comment by jesper-raemaekers** [comment]
I'm sure an option to disable it is possible. Does this error cause problems somewhere?
For the python but it should fail and continue.

**Comment by jesper-raemaekers** [comment]
I've opted to insert a check before executing the query. This failure should not longer happen.
