### ISSUE TITLE
Login to polarion fails

### ISSUE THREAD

**Issue by Mighty-Panther** [jesper-raemaekers/python-polarion#97]
Since this month the login to polarion does not work anymore, I get the following error message.

**Forcing soap:address location to HTTPS
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was closed by the remote host', None, 10054, None))**

I can still sign up through the website. 
The polarion admistrator could not or would not help me.

I would be grateful for any ideas.

Thanks!

Ps: This tool has been a great help and relief for me so far.

__________________________________________________________________________________________________________________

Python: 3.9
polarion-1.1.0
zeep-4.2.1
urllib3-1.26.13
__________________________________________________________________________________________________________________
Traceback (most recent call last):
  File "C:\examplePolarion\lib\site-packages\requests\adapters.py", line 440, in send
      resp = conn.urlopen(
  File "C:\examplePolarion\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
      retries = retries.increment(
  File "C:\examplePolarion\lib\site-packages\urllib3\util\retry.py", line 550, in increment
      raise six.reraise(type(error), error, _stacktrace)
  File "C:\examplePolarion\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
      raise value.with_traceback(tb)
  File "C:\examplePolarion\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
      httplib_response = self._make_request(
  File "C:\examplePolarion\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
      self._validate_conn(conn)
  File "C:\examplePolarion\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
      conn.connect()
  File "C:\examplePolarion\lib\site-packages\urllib3\connection.py", line 414, in connect
      self.sock = ssl_wrap_socket(
  File "C:\examplePolarion\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
      ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\examplePolarion\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
      return ssl_context.wrap_socket(sock)
  File "C:\Apps\Python39\lib\ssl.py", line 500, in wrap_socket
      return self.sslsocket_class._create(
  File "C:\Apps\Python39\lib\ssl.py", line 1040, in _create
      self.do_handshake()
  File "C:\Apps\Python39\lib\ssl.py", line 1309, in do_handshake
      self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was closed by the remote host

**Comment by jesper-raemaekers** [comment]
I'm not sure what to do here, the error message points to your server. Was it working before with the exact same versions of python, polarion and zeep?

**Comment by Mighty-Panther** [comment]
First of all, thank you for answering my message. 👍

Yes, everything was working fine with your python polarion package until last month. 
So I also believe that the problem lies with this server. 🤷🏼‍♂️

As already mentioned, there was no answer from the admin so far.
I was hoping that the error message would give you an idea of what I might have to do differently with the login. 🤔
